language: python

python:
  - 2.7
  - 3.5
  - 3.6
  - "nightly"

install:
  - pip install -e .
  - pip install python-slugify

script:
  - python -m tests.spec
  - python -m tests.spec -f gfm
  - python -m unittest discover

notifications:
  email: false
