language: python

python:
  - 3.4
  - 3.5
  - 3.6

install:
  - pip install -e .
  - pip install python-slugify

script:
  - python -m tests.spec
  - python -m tests.spec -f gfm
  - python -m unittest

notifications:
  email: false
