language: python
sudo: false
cache: pip
dist: trusty

install: pip install tox-travis
script: tox

jobs:
  include:
    - stage: test
    - python: "3.7"
      dist: xenial
      sudo: required
    - python: "3.6"
    - python: "3.5"
    - python: "2.7"
