[tool.poetry]
name = "marko"
version = "0.7.1"
description = "A markdown parser with high extensibility."
authors = ["Frost Ming <mianghong@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/frostming/marko"
repository = "https://github.com/frostming/marko"
documentation = "https://marko-py.readthedocs.io"

keywords = ["markdown", "commonmark", "parser"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    'Operating System :: OS Independent',
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 2",
    "Programming Language :: Python :: 2.7",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.5",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7"
]

[tool.poetry.dependencies]
python = "~2.7 || ^3.5"
"backports.html" = {version="^1.0.0", python="~2.7"}
python-slugify = {version = "^4.0.0", optional = true}
pygments = {version = "^2.5.2", optional = true}

[tool.poetry.dev-dependencies]
flake8 = "^3.7.9"
mypy = {version = "^0.761", python = ">=3.6"}
pytest = {version = "^5.3.2", python = "^3.6"}
sphinx = {version = "^2.3.1", python = "^3.6"}
pytest-cov = {version = "^2.8.1", python = "^3.6"}

[tool.poetry.extras]
toc = ["python-slugify"]
codehilite = ["pygments"]

[tool.poetry.scripts]
marko = "marko.cli:main"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
