name: Tests

on: [push, pull_request]

jobs:
  Linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Linting
        run: |
          pip install mypy flake8
          flake8
          mypy .

  Testing:
    needs: Linting
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install PDM
        run: pip install --upgrade pdm
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pdm use ${{ matrix.python-version }}
          pip install wheel
          pdm install -d -s toc -s codehilite
      - name: Run Tests
        run: |
          pdm run pytest --cov marko tests
      - name: Report code coverage
        if: matrix.os != 'windows-latest'
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
        run: |
          pip install codecov
          pdm run coverage report
          pdm run coverage xml
          codecov
