name: Tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  Linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Linting
        run: |
          pip install mypy flake8
          flake8
          mypy .

  Testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Set Variables
        id: set_variables
        run: |
          echo "::set-output name=PIP_CACHE::$(pip cache dir)"
      - name: Cache PIP
        uses: actions/cache@v2
        with:
          path: ${{ steps.set_variables.outputs.PIP_CACHE }}
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}
      - name: Cache PEP 582 packages
        uses: actions/cache@v2
        with:
          path: __pypackages__
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-packages-${{ matrix.python-version }}-${{ hashFiles('pdm.lock') }}
          restore-keys: |
            ${{ runner.os }}-packages-${{ matrix.python-version }}-
            ${{ runner.os }}-packages-
      - name: Install PDM
        run: python -m pip install --upgrade --pre pdm
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pdm use -f ${{ matrix.python-version }}
          pdm sync -dvvv -s toc -s codehilite
      - name: Run Tests
        run: |
          pdm run pytest --cov=marko/ --cov-report=xml tests
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
