name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release-pypi:
    name: release-pypi
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
          architecture: "x64"
      - name: Install Current PDM
        run: |
          pip install -U pip
          pip install --pre pdm
      - name: Build artifacts
        run: |
          pdm build -v
      - name: Test Build
        run: |
          python3 -m venv fresh_env
          . fresh_env/bin/activate
          pip install dist/*.whl
          output = $(echo '# hello world' | fresh_env/bin/marko | xargs)
          [[ $output == "<h1>hello world</h1>" ]] || false
      - name: Upload to Pypi
        run: |
          pip install twine
          twine upload --username __token__ --password ${{ secrets.PYPI_TOKEN }} dist/*
